services:
  vote:
    build: vote
    scale: 2
    ports:
      - 8080:8080

   redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGODB_URI: $MONGODB_URI
      OWNER_ID: $OWNER_ID
      LOG_CHANNEL: $LOG_CHANNEL
