version: "1.4"
services:  
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGODB_URI: $MONGODB_URI
      OWNER_ID: $OWNER_ID
      LOG_CHANNEL: $LOG_CHANNEL
